#!/usr/bin/env python3
"""
Merge Python modules into a single Kaggle-uploadable Jupyter notebook.

Reads .py files from a package directory, strips relative imports,
and combines them into one .ipynb with optional install and entry-point cells.

Usage:
    merge_modules.py --pkg-dir my_package/ -o output.ipynb
    merge_modules.py --pkg-dir my_package/ --order config.py,model.py,train.py -o out.ipynb
    merge_modules.py --pkg-dir my_package/ -o out.ipynb --pip-packages "torch numpy"
    merge_modules.py --pkg-dir my_package/ -o out.ipynb --no-install-cell
    merge_modules.py --pkg-dir my_package/ -o out.ipynb --entry-prep "data = load()" --entry-call "main(data)"
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def read_module(filepath: Path) -> str:
    """Read a module file, strip shebang and __future__ imports."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    if lines and lines[0].startswith("#!/"):
        lines = lines[1:]

    filtered = [line for line in lines if "from __future__" not in line]
    return "\n".join(filtered).strip()


def resolve_imports(content: str) -> str:
    """Strip relative imports — all names are in the same namespace after merge.

    Handles both single-line and multi-line parenthesized imports:
        from .config import cfg, DEVICE          # single-line
        from .quant import (A, B, C,             # multi-line start
                            D, E, F,             # continuation
                            G)                   # closing paren
    """
    lines = content.split("\n")
    result = []
    in_multiline_import = False
    paren_depth = 0
    for line in lines:
        # Multi-line paren import MUST be checked before single-line match,
        # because "from .quant import (A, B" also matches the single-line regex.
        if re.match(r"^\s*from\s+\.([\w]+)\s+import\s+\(.*$", line):
            paren_depth = line.count("(") - line.count(")")
            if paren_depth > 0:
                in_multiline_import = True
            continue
        # Inside multi-line import: skip continuation lines until parens close
        if in_multiline_import:
            paren_depth += line.count("(") - line.count(")")
            if paren_depth <= 0:
                in_multiline_import = False
            continue
        # from .module import ... (single-line, no parens)
        if re.match(r"^\s*from\s+\.([\w]+)\s+import\s+.*$", line):
            continue
        # from . import xxx
        if re.match(r"^\s*from\s+\.\s+import\s+.*$", line):
            continue
        result.append(line)
    return "\n".join(result)


def merge_modules(pkg_dir: Path, order: list[str]) -> str:
    """Merge modules in specified dependency order."""
    merged_parts = []

    for mod_name in order:
        mod_path = pkg_dir / mod_name
        if not mod_path.exists():
            print(f"[WARNING] Module not found: {mod_path}", file=sys.stderr)
            continue

        content = read_module(mod_path)
        content = resolve_imports(content)

        merged_parts.append(f"\n# {'='*60}")
        merged_parts.append(f"# Module: {mod_name}")
        merged_parts.append(f"# {'='*60}\n")
        merged_parts.append(content)
        merged_parts.append("")

    return "\n".join(merged_parts)


def build_notebook(
    code_content: str,
    pip_packages: str | None,
    include_install: bool,
    entry_prep: str | None,
    entry_call: str | None,
) -> dict:
    """Build notebook JSON from merged code."""
    cells = []

    # Markdown intro
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "id": "cell-0000",
        "source": [
            "# Merged Notebook (auto-generated)\n",
            "\n",
            "> This file was generated by `merge_modules.py`. "
            "Do not edit directly — modify source modules and re-merge.\n",
        ]
    })

    cell_idx = 1

    # Install cell
    if include_install and pip_packages:
        cells.append({
            "cell_type": "code",
            "metadata": {},
            "id": f"cell-{cell_idx:04d}",
            "execution_count": None,
            "outputs": [],
            "source": [
                "%%bash\n",
                "export PYTORCH_ALLOC_CONF=expandable_segments:True\n",
                f"pip install -q {pip_packages}",
            ]
        })
        cell_idx += 1

    # Main code cell
    cells.append({
        "cell_type": "code",
        "metadata": {},
        "id": f"cell-{cell_idx:04d}",
        "execution_count": None,
        "outputs": [],
        "source": [code_content],
    })
    cell_idx += 1

    # Entry prep cell
    if entry_prep:
        cells.append({
            "cell_type": "code",
            "metadata": {},
            "id": f"cell-{cell_idx:04d}",
            "execution_count": None,
            "outputs": [],
            "source": [entry_prep],
        })
        cell_idx += 1

    # Entry call cell
    if entry_call:
        cells.append({
            "cell_type": "code",
            "metadata": {},
            "id": f"cell-{cell_idx:04d}",
            "execution_count": None,
            "outputs": [],
            "source": [entry_call],
        })
        cell_idx += 1

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": sys.version.split()[0],
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge Python modules into a single Kaggle notebook."
    )
    parser.add_argument(
        "--pkg-dir", type=Path, required=True,
        help="Path to the Python package directory containing .py modules."
    )
    parser.add_argument(
        "--order", type=str, default=None,
        help="Comma-separated list of module filenames in dependency order "
             "(e.g., config.py,model.py,train.py). "
             "If omitted, auto-discovers .py files (excluding __init__.py) alphabetically."
    )
    parser.add_argument(
        "-o", "--output", type=Path, required=True,
        help="Output .ipynb path."
    )
    parser.add_argument(
        "--pip-packages", type=str, default=None,
        help="Pip packages for install cell (e.g., 'torch numpy asteroid')."
    )
    parser.add_argument(
        "--no-install-cell", action="store_true",
        help="Skip the %%bash pip install cell."
    )
    parser.add_argument(
        "--entry-prep", type=str, default=None,
        help="Code to run before main entry (e.g., 'train_loader, val_loader = build_dataloaders()')."
    )
    parser.add_argument(
        "--entry-call", type=str, default=None,
        help="Main entry call (e.g., 'main(train_loader, val_loader)')."
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    pkg_dir = args.pkg_dir.resolve()

    if not pkg_dir.is_dir():
        print(f"[ERROR] Package directory not found: {pkg_dir}", file=sys.stderr)
        return 1

    # Determine module order
    if args.order:
        order = [m.strip() for m in args.order.split(",")]
    else:
        order = sorted(
            f.name for f in pkg_dir.glob("*.py")
            if f.name != "__init__.py"
        )
        print(f"[INFO] Auto-discovered modules: {order}")

    # Merge
    code_content = merge_modules(pkg_dir, order)

    # Build notebook
    notebook = build_notebook(
        code_content,
        pip_packages=args.pip_packages,
        include_install=not args.no_install_cell,
        entry_prep=args.entry_prep,
        entry_call=args.entry_call,
    )

    # Write
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)

    # Summary
    total_lines = code_content.count("\n")
    print(f"[OK] Notebook generated: {args.output}")
    print(f"     Cells: {len(notebook['cells'])}")
    print(f"     Code lines: {total_lines}")
    print(f"     Modules merged: {len(order)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
